import 'dart:async';
import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:duck_flutter/model/GirlModel.dart';
import 'package:duck_flutter/model/NewsModel.dart';

var dio = new Dio();

Future<String> getStringFully() async {
  Response response;
  try {
    response = await dio.get("http://gank.io/api/data/%E7%A6%8F%E5%88%A9/10/1");
    print("${response.toString()}");

    return response.toString();
  } catch (e) {
    print(e.toString());
    return "空";
  }
}

Future<List<GirlData>> getGirlArray() async {
  Response response;
  try {
    response = await dio.get("http://gank.io/api/data/%E7%A6%8F%E5%88%A9/10/1");
    print("${response.toString()}");

    Map<String, dynamic> user = json.decode(response.toString());
    GirlModel a = GirlModel.fromJson(user);

    List<GirlData> searchIds = new List();
    searchIds.addAll(a.results);

    return searchIds;
  } catch (e) {
    print(e.toString());
    return new List();
  }
}

Future<String> getNewsString() async {
  Response response;
  try {
    response = await dio.get("http://ali-news.showapi.com/newsList",
        options: Options(
            headers: FormData.from({
          "Authorization": "APPCODE 9b3495de5ea3405ca3b57cf527ff29b6",
          "channelId": "5572a109b3cdc86cf39001e0",
        })));

//    print("${response.toString()}");

    return response.toString();
  } catch (e) {
    print(e.toString());
    return "空";
  }
}

//取得新聞資訊
Future<List<Contentlist>> getNewsListAPI() async {
  Response response;
  try {
    response = await dio.get("http://ali-news.showapi.com/newsList",
        options: Options(
            connectTimeout: 10000,
            headers: FormData.from({
              "Authorization": "APPCODE 9b3495de5ea3405ca3b57cf527ff29b6",
              "channelId": "5572a109b3cdc86cf39001e0",
            })));

    print("${response.toString()}");

    Map<String, dynamic> req = json.decode(response.toString());
    Autogenerated a = Autogenerated.fromJson(req);

    return a.showapiResBody.pagebean.contentlist;
  } catch (e) {
    print(e.toString());
    return null;
  }
}
